Repository CamyH/SEM-SET08103, pull requests merged in 2021-03, with the labels that each got.

#88 Consolidation of info in use cases
  use-cases/languages/Languages Reporting System.puml
  use-cases/languages/use-case32.md
  use-cases/languages/use-case33.md
  use-cases/languages/use-case34.md
  use-cases/languages/use-case35.md
  use-cases/languages/use-case36.md
  use-cases/population/Population Reporting System.puml
  use-cases/population/use-case23.md
  use-cases/population/use-case24.md
  use-cases/population/use-case25.md
  use-cases/population/use-case26.md
  use-cases/population/use-case27.md
  use-cases/population/use-case28.md
  use-cases/population/use-case29.md
  use-cases/population/use-case30.md
  use-cases/population/use-case31.md
Labels: documentation

#109 Language Reports + Unit Tests
  .gitignore
  SEM-SET08103.iml
  pom.xml
  src/main/java/com/napier/sem/App.java
  src/main/java/com/napier/sem/report/Reports.java
  src/main/java/com/napier/sem/sql/Sql.java
  src/main/java/com/napier/sem/world/Languages.java
  src/test/java/com/napier/sem/LanguagesTests.java
Labels: new feature

#113 All language tests completed.
  src/main/java/com/napier/sem/App.java
  src/main/java/com/napier/sem/db/DbConnection.java
  src/test/java/com/napier/sem/LanguagesTests.java
Labels: tests

#112 Additional function tests complete
  src/main/java/com/napier/sem/App.java
  src/test/java/com/napier/sem/AdditionalFunctionsTests.java
Labels: tests

#116 Feature/country and population data tests
  src/main/java/com/napier/sem/App.java
  src/test/java/com/napier/sem/CountryTests.java
  src/test/java/com/napier/sem/PopulationDataTests.java
Labels: tests

#117 Updated capital city tests merge
  Dockerfile
  pom.xml
  src/main/java/com/napier/sem/db/DbConnection.java
  src/main/java/com/napier/sem/report/Reports.java
  src/test/java/com/napier/sem/CapitalTests.java
Labels: tests

#122 Develop to release after code cleanup and final SQL implemented
  .gitignore
  SEM-SET08103.iml
  pom.xml
  src/main/java/com/napier/sem/App.java
  src/main/java/com/napier/sem/db/DbConnection.java
  src/main/java/com/napier/sem/report/Reports.java
  src/main/java/com/napier/sem/sql/Sql.java
  src/main/java/com/napier/sem/world/City.java
  src/main/java/com/napier/sem/world/Country.java
  src/main/java/com/napier/sem/world/Languages.java
  src/main/java/com/napier/sem/world/PopulationData.java
  src/test/java/com/napier/sem/CityTests.java
  src/test/java/com/napier/sem/CountryTests.java
  src/test/java/com/napier/sem/LanguagesTests.java
  src/test/java/com/napier/sem/PopulationDataTests.java
Labels: enhancement

#123 Code cleanup & final SQL implementation
  .gitignore
  SEM-SET08103.iml
  pom.xml
  src/main/java/com/napier/sem/App.java
  src/main/java/com/napier/sem/db/DbConnection.java
  src/main/java/com/napier/sem/report/Reports.java
  src/main/java/com/napier/sem/sql/Sql.java
  src/main/java/com/napier/sem/world/City.java
  src/main/java/com/napier/sem/world/Country.java
  src/main/java/com/napier/sem/world/Languages.java
  src/main/java/com/napier/sem/world/PopulationData.java
  src/test/java/com/napier/sem/CityTests.java
  src/test/java/com/napier/sem/CountryTests.java
  src/test/java/com/napier/sem/LanguagesTests.java
  src/test/java/com/napier/sem/PopulationDataTests.java
Labels: enhancement

#125 Updated travis working and all test functions completed and working
  .gitignore
  .gitmodules
  .travis.yml
  Dockerfile
  README.md
  pom.xml
  src/main/java/com/napier/sem/App.java
  src/main/java/com/napier/sem/db/DbConnection.java
  src/main/java/com/napier/sem/report/Reports.java
  src/main/java/com/napier/sem/sql/Sql.java
  src/test/java/com/napier/sem/AppIntegrationTest.java
  src/test/java/com/napier/sem/AppTest.java
  src/test/java/com/napier/sem/CityTests.java
  src/test/java/com/napier/sem/CountryTests.java
  src/test/java/com/napier/sem/LanguagesTests.java
Labels: enhancement

#127 Release to main - All working release to main of SQL & test functions working in travis
  .gitignore
  .gitmodules
  .travis.yml
  Dockerfile
  README.md
  pom.xml
  src/main/java/com/napier/sem/App.java
  src/main/java/com/napier/sem/db/DbConnection.java
  src/main/java/com/napier/sem/report/Reports.java
  src/main/java/com/napier/sem/sql/Sql.java
  src/test/java/com/napier/sem/AppIntegrationTest.java
  src/test/java/com/napier/sem/AppTest.java
  src/test/java/com/napier/sem/CityTests.java
  src/test/java/com/napier/sem/CountryTests.java
  src/test/java/com/napier/sem/LanguagesTests.java
Labels: enhancement

#136 Fix/travis deploy stage
  .travis.yml
  pom.xml
  src/main/java/com/napier/sem/db/DbConnection.java
Labels: bug

#138 Updated deploy script for GitHub release
  .travis.yml
  pom.xml
  src/main/java/com/napier/sem/App.java
  src/main/java/com/napier/sem/db/DbConnection.java
Labels: new feature
