Repository CamyH/SEM-SET08103, pull requests merged in 2021-02, with the labels that each got.

#37 Develop to release merge
  .travis.yml
  CODE_OF_CONDUCT.md
  GroupProj.iml
  LICENCE
  SEM-SET08103.iml
  db/Dockerfile
  db/world.sql
  docker-compose.yml
  pom.xml
  src/main/java/com/napier/sem/App.java
  src/main/java/com/napier/sem/ConsoleUtils.java
  src/main/java/com/napier/sem/DbConnection.java
  src/main/java/com/napier/sem/Menu.java
  src/main/java/com/napier/sem/MenuChoice.java
  src/main/java/com/napier/sem/MenuItem.java
  src/main/java/com/napier/sem/MenuSelection.java
  target/sem-set08103-0.1.0.2-jar-with-dependencies.jar
  target/sem-set08103-0.1.0.2.jar
Labels: enhancement

#66 Feature/additional info reports
  Dockerfile
  README.md
  SEM-SET08103.iml
  pom.xml
  src/main/java/com/napier/sem/App.java
  src/main/java/com/napier/sem/report/Reports.java
  src/main/java/com/napier/sem/sql/AdditionalReports.java
  src/main/java/com/napier/sem/world/City.java
  src/main/java/com/napier/sem/world/PopulationData.java
Labels: new features

#70 Feature/use cases cities completed
  src/main/java/com/napier/sem/App.java
  use-cases/cities/use-case07.md
  use-cases/cities/use-case08.md
  use-cases/cities/use-case09.md
  use-cases/cities/use-case10.md
  use-cases/cities/use-case11.md
  use-cases/cities/use-case12.md
  use-cases/cities/use-case13.md
  use-cases/cities/use-case14.md
  use-cases/cities/use-case15.md
  use-cases/cities/use-case16.md
Labels: documentation

#81 Feature/citiesdiagram case diagram complete
  src/main/java/com/napier/sem/report/Reports.java
  use-cases/cities/Global Reporting System.puml
Labels: documentation

#83 Feature/country use cases
  use-cases/countries/use-case1.md
  use-cases/countries/use-case2.md
  use-cases/countries/use-case3.md
  use-cases/countries/use-case4.md
  use-cases/countries/use-case5.md
  use-cases/countries/use-case6.md
  use-cases/countries/use-cases.puml
Labels: documentation
