Repository CamyH/SEM-SET08103, pull requests merged in 2021-04, with the labels that each got.

#139 Latest Release
  .travis.yml
  pom.xml
  src/main/java/com/napier/sem/App.java
  src/main/java/com/napier/sem/db/DbConnection.java
Labels: new feature

#149 Create SECURITY.md
  SECURITY.md
Labels: documentation

#150 Create SUPPORT.md
  SUPPORT.md
Labels: documentation

#151 Create pull_request_template.md
  pull_request_template.md
Labels: documentation

#157 Final Check of app main with 4 example functions.
  src/main/java/com/napier/sem/App.java
Labels: enhancement

#158 Changed DB connection request on app integration test file.
  src/test/java/com/napier/sem/AppIntegrationTest.java
Labels: addition, bug

#159 Final release
  .gitignore
  .travis.yml
  README.md
  pom.xml
  screenshots/1.png
  screenshots/10.png
  screenshots/11.png
  screenshots/12.png
  screenshots/13.png
  screenshots/14.png
  screenshots/15.png
  screenshots/16.png
  screenshots/17.png
  screenshots/18.png
  screenshots/19.png
  screenshots/2.png
  screenshots/20.png
  screenshots/21.png
  screenshots/22.png
  screenshots/23.png
  screenshots/24.png
  screenshots/25.png
  screenshots/26.png
  screenshots/27.png
  screenshots/28.png
  screenshots/29.png
  screenshots/3.png
  screenshots/30.png
  screenshots/31.png
  screenshots/32.png
  screenshots/33.png
  screenshots/34.png
  screenshots/35.png
  screenshots/36.png
  screenshots/4.png
  screenshots/5.png
  screenshots/6.png
  screenshots/7.png
  screenshots/8.png
  screenshots/9.png
  src/main/java/com/napier/sem/App.java
  src/main/java/com/napier/sem/db/DbConnection.java
  src/main/java/com/napier/sem/report/Reports.java
  src/test/java/com/napier/sem/AppIntegrationTest.java
  src/test/java/com/napier/sem/AppTest.java
Labels: enhancement

#163 Fix/readme
  .travis.yml
  README.md
  pom.xml
  src/main/java/com/napier/sem/report/Reports.java
Labels: documentation

#164 Latest changes merged into release
  .travis.yml
  README.md
  pom.xml
  src/main/java/com/napier/sem/report/Reports.java
Labels: documentation

#165 Latest fixes and changes ready for release
  .travis.yml
  README.md
  pom.xml
  src/main/java/com/napier/sem/report/Reports.java
Labels: documentation
